In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = '/content/cross-validation.csv'
df = pd.read_csv(data)
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [ ]:
df['Loan_Status'].replace({'Y':1, 'N':0}, inplace=True)
df['Gender'].replace({'Male':1, 'Female':0}, inplace=True)
df['Married'].replace({'Yes':1, 'No':0}, inplace=True)
df['Dependents'].replace({'3+':3}, inplace=True)
df['Education'].replace({'Graduate':1, 'Not Graduate':0}, inplace=True)
df['Self_Employed'].replace({'Yes':1, 'No':0}, inplace=True)
df['Property_Area'].replace({'Urban':2, 'Rural':1, 'Semiurban':0}, inplace=True)
df = df.drop('Loan_ID', axis=1)

In [ ]:
df = df.fillna(0)

In [ ]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1.0,0.0,0,1,0.0,5849,0.0,0.0,360.0,1.0,2,1
1,1.0,1.0,1,1,0.0,4583,1508.0,128.0,360.0,1.0,1,0
2,1.0,1.0,0,1,1.0,3000,0.0,66.0,360.0,1.0,2,1
3,1.0,1.0,0,0,0.0,2583,2358.0,120.0,360.0,1.0,2,1
4,1.0,0.0,0,1,0.0,6000,0.0,141.0,360.0,1.0,2,1

In [ ]:
X = df.drop(columns=['Loan_Status']).values
y = df['Loan_Status'].values
print(X.shape)
print(y.shape)

(614, 11)
(614,)

In [ ]:
X

array([[1.0, 0.0, '0', ..., 360.0, 1.0, 2],
       [1.0, 1.0, '1', ..., 360.0, 1.0, 1],
       [1.0, 1.0, '0', ..., 360.0, 1.0, 2],
       ...,
       [1.0, 1.0, '1', ..., 360.0, 1.0, 2],
       [1.0, 1.0, '2', ..., 360.0, 1.0, 2],
       [0.0, 0.0, '0', ..., 360.0, 0.0, 0]], dtype=object)

In [ ]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
import warnings


# Ignore all warnings (not recommended)
warnings.filterwarnings("ignore")

In [ ]:
import numpy as np

# Step 1: Split the dataset into 80% for training and 20% for testing

# Set the random seed for reproducibility
np.random.seed(42)

# Shuffle the data
shuffled_indices = np.random.permutation(len(X))
X_shuffled = X[shuffled_indices]
y_shuffled = y[shuffled_indices]

# Split point for training and testing
split_point = int(0.8 * len(X_shuffled))

# Split the data
X_train, X_test = X_shuffled[:split_point], X_shuffled[split_point:]
y_train, y_test = y_shuffled[:split_point], y_shuffled[split_point:]

# Step 2: Train a Logistic Regression model with no regularization
from sklearn.linear_model import LogisticRegression

# Create the logistic regression model
model = LogisticRegression(solver='saga', penalty='none')

# Fit the model to the training data
model.fit(X_train, y_train)

# Step 3: Cross-validate the classifier with 5-folds
K = 5  # Number of folds
fold_size = len(X_train) // K

accuracies = []
precisions = []
recalls = []

for i in range(K):
    # Define the start and end indices for the current fold
    start = i * fold_size
    end = (i + 1) * fold_size

    # Create training and validation sets for this fold
    X_valid_fold = X_train[start:end]
    y_valid_fold = y_train[start:end]

    # Create training set for this fold (excluding the current fold)
    X_train_fold = np.concatenate([X_train[:start], X_train[end:]])
    y_train_fold = np.concatenate([y_train[:start], y_train[end:]])

    # Train the model on the training fold
    model.fit(X_train_fold, y_train_fold)

    # Predict on the validation fold
    y_pred_fold = model.predict(X_valid_fold)

    # Calculate accuracy, precision, and recall for class 1 (good)
    accuracy_fold = np.mean(y_pred_fold == y_valid_fold)
    precision_fold = np.sum((y_pred_fold == 1) & (y_valid_fold == 1)) / np.sum(y_pred_fold == 1)
    recall_fold = np.sum((y_pred_fold == 1) & (y_valid_fold == 1)) / np.sum(y_valid_fold == 1)

    accuracies.append(accuracy_fold)
    precisions.append(precision_fold)
    recalls.append(recall_fold)

# Calculate the mean accuracy, precision, and recall for class 1 (good)
mean_accuracy = np.mean(accuracies)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)

# Print the results
print(f"Mean Accuracy: {mean_accuracy:.2f}")
print(f"Mean Precision for Class 1 (good): {mean_precision:.2f}")
print(f"Mean Recall for Class 1 (good): {mean_recall:.2f}")

Mean Accuracy: 0.68
Mean Precision for Class 1 (good): 0.68
Mean Recall for Class 1 (good): 1.00